version: '3.8'

services:
  # Django Web Application
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=messaging_app.settings
      - DATABASE_URL=mysql://root:123456@db:3306/messaging_app
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - messaging_network
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

  # MySQL Database
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=messaging_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - messaging_network

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - messaging_network

volumes:
  mysql_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  messaging_network:
    driver: bridge

 