apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"  # 20% traffic to green
spec:
  type: ClusterIP
  selector:
    app: messaging-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-blue
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    version: blue
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-green
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    version: green
  ports:
    - name: http
      port: 80
      targetPort: 8000